name: e_commerce_front_end
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_gen: ^5.1.0+1
  flutter_svg: 1.1.6
  gap: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: 2.3.2  
  flutter_gen_runner: 5.1.0+1

flutter_gen:
  output: lib/gen/ 
  line_length: 80 
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/svg/

